### PR TITLE
Fixing a bug with enter key.

### PR DESCRIPTION
**Pull request by jsixface**
The keystrokes cannot be captured with the soft keyboard. The only way this could be achieved is to change the keyboard action to done and you see a tick mark in please of the enter key.

### CODE REVIEW

**Comment by jsixface** [comment]
Hey @TheHawaiianKoala @bagajohny  Can you guys check if this fix works properly ? 
And how do you feel about the enter button now has a check mark ?

**Comment by bagajohny** [comment]
> Hey @TheHawaiianKoala @bagajohny Can you guys check if this fix works properly ? And how do you feel about the enter button now has a check mark ?

Which app version? I dont see any change in 1.4.5

Is there any specific syntax to check it?

**Comment by jsixface** [comment]
It's not released yet. 
Here's the APK - https://github.com/quillpad/quillpad/suites/9714196272/artifacts/465795363

**Comment by bagajohny** [comment]
> It's not released yet. Here's the APK - https://github.com/quillpad/quillpad/suites/9714196272/artifacts/465795363

So it works but for specific cases. I dont know if it was intentional but I am just stating what I observed.
1. It works for numbered list only in case there is a "." after the number. It doesn't work if there is a ")" or "]" after the number.
2. It works for numbered list but only if you type at least one letter. Space or multiple spaces do not count.
3. for non numbered list it works if you have "-". I couldnt find any other symbol that works.
4. for checkmarks it works when you have at least one letter. same as point no 2.

As for the enter button, I feel the enter arrow symbol feels more accurate than the right check mark.

**Comment by jsixface** [comment]
> it works when you have at least one letter.
> 2. It works for numbered list but only if you type at least one letter. Space or multiple spaces do not count.

This is a typical behaviour in any formatted editor like word or google docs. You press 'enter' in a list to add an item to list. If you press enter again without typing anything, that means you are done with the list. That's why the newly added list prefix is removed.

> 1. It works for numbered list only in case there is a "." after the number. It doesn't work if there is a ")" or "]" after the number.

")" and "]" are not a part of [markdown specs](https://www.markdownguide.org/basic-syntax#lists-1)


> 3. for non numbered list it works if you have "-". I couldnt find any other symbol that works.

This is something I forgot about. I have to add `+` and `*` as supported lists.

> As for the enter button, I feel the enter arrow symbol feels more accurate than the right check mark.

This was not a choice I had. The text view did not send an event when 'enter' key was there, it enters a new line. I have to change it to a 'Done' key so that it sends an event that I can capture and process the new line entry. 

I will fix the issue for `+` and `*` and create a new PR and see if I can bring back the enter arrow key with some other changes.

**Comment by jsixface** [comment]
@bagajohny Can you check if this build fixes the issue https://github.com/quillpad/quillpad/suites/9787029939/artifacts/470660481

**Comment by jsixface** [comment]
Numbered list and check box list.
Other than these nothing else. Thank you.

**Pull request merged**
