### PR TITLE
Compact notes list (#42)

### LINKED ISSUE #42: Compact notes list
@jsixface 

First, thanks for maintaining and developing this project.

I would like to suggest a simple enhancement- a new option in settings for showing only notes titles in notes list, without showing part of the notes text and notes tags. I mean something like that:

Screenshot_20221130-164146

I prefer a compact notes list as shown in the screenshot above. With an option for compact notes list (only notes titles shown) there would be less scrolling when the notes list grows bigger.

Regards

### PR DESCRIPTION
**Pull request by nofishonfriday**
This PR adds a per note setting to hide the text body in the notes list ('compact preview').
I find this more flexible than having a global (for all notes) compact/full preview setting, so some notes can be made compact while others have full preview.
Also works for tasks (lists).
Default is full preview (as is currently), so there's no change in default behaviour.

Demo:
compact preview

Dev note:
Because I added a new `Note` field (`isCompactPreview`) I had to do a database migration.
I've tested on the emulator and my actual device that the migration works correctly.
Still a sensitive topic though (to not accidently wipe existing users' data) so probably should be tested on other devices too before shipping.
(First time I've coded this.)

TODO (maybe): new icons for full/compact preview, currently it uses existing `ic_preview` for both.
(Making icons is out of my ability. :))

closes #42

### CODE REVIEW

**Comment by nofishonfriday** [comment]
Misunderstanding from my side, will rework.

**Comment by nofishonfriday** [comment]
Sorry, I meant to close the other PR.

**Comment by nofishonfriday** [comment]
I have this mod running on my actual phone now.
DB migration (of existing notes) worked fine but I realize now there isn't any visual difference in the notes preview screen between an empty note (title only) and a note which has some content in the body but is compacted, both only show the title in this case.
Hm...maybe compacted notes should show first line of ontent if not empty?
Thoughts?

**Comment by jsixface** [comment]
I think it is fine to not differentiate compacted notes from the empty bodied notes. It is understood that you'll only see the title and let's not over complicate it.

I am little bit concerned about the db migration though - I haven't tested it out yet. There's slightly less than 500 users using the app. 

I'm going to test by taking a backup, updating the app and migrating the db, take a backup again and compare both the backups. I'd ask you test the same as well.

**Comment by nofishonfriday** [comment]
> I'm going to test by taking a backup, updating the app and migrating the db, take a backup again and compare both the backups. I'd ask you test the same as well.

Looking ok here.
compare

**Comment by landry314** [comment]
I don't see this option and I would love it to be universal. I want a setting to make all notes just display the title.

**Comment by jsixface** [comment]
I tested it and it is good. I'll merge this. Thank you for your work @nofishonfriday

**Review by jsixface — APPROVED** [review]

**Comment by nofishonfriday** [comment]
Thanks for testing and merging @jsixface.
The good thing is, if more db migrating should be necessary for future development we now have already a (succesfukl) test case. :)

Regarding @landry314's comment:
I think I could add a menu item in the 'multiple notes selected' menu to compact/full preview all selected notes at once. 
As there is already a 'Select all' item in the preview screen it would be quick to compact/full preview all notes at once this way.
Will open a new PR for it.

**Comment by jsixface** [comment]
Yeah. That's great. I had migrating planned as well. Check out the `local-storage` branch

**Pull request merged**
