### PR TITLE
Fix #140: Correct misleading deletion messages when the "Delete notes in bin" option is set to "Never"

### LINKED ISSUE #140: Misleading Deletion Messages
When the "Delete notes in bin" option is set to "Never", some messages mislead the user into thinking the option is actually set to "Instantly":
- When the bin is empty, the placeholder message reads "Notes are set to be deleted instantly".
- When deleting a note, the toast reads "Deleted note permanently", but the note has actually been moved to the bin.

### PR DESCRIPTION
**Pull request by nofishonfriday**
closes #140

### CODE REVIEW

**Comment by nofishonfriday** [comment]
> I'd also improve the following strings in _app/src/main/res/values/strings.xml_:
> 174. Notes are set to be deleted immediately, so they do not appear here.\nYou can change this in the Settings.
> 175. Notes are set to never be deleted.\nYou can change this in the Settings.

Can do, but I'm not sure how localization (translations) is handled if we change the default text of an already existing and translated string (174).
Should I then also remove all the existing translations in my PR? (@jsixface)

> EDIT: I just made a new feature request (https://github.com/quillpad/quillpad/issues/156). If you'd like to make an access to 
> this setting easier, we could get rid of these 'You can change this in the Settings' lines.

Good suggestion imo but I don't promise anything. :D

**Comment by jsixface** [comment]
> Should I then also remove all the existing translations in my PR? 

If you're removing strings in the main file, yes, you can should remove them from translations as well.
I'd also add translation using an online translator for the line you added. Some close enough translation is better than people seeing it in English.

**Comment by nofishonfriday** [comment]
I've added (online translator) translations for the newly added string (175), but leave existing and already translated 174 as is (for now) for simplicity.

**Comment by jsixface** [comment]
> I found this bulk translater which makes it a bit faster.
> https://bulktranslator.com/

This is very cool. Thank you.

**Pull request merged**
